"""DataLens dashboard data endpoints.

Provides JSON-formatted data suitable for Yandex DataLens API Connector.
Includes aggregated statistics by class, district, status, and response time.
"""

from __future__ import annotations

from cloud.analytics.sample_incidents import generate_incidents

_SEED = 42


def get_datalens_incidents() -> list[dict]:
    """Return enriched incidents for DataLens.

    Response times are generated by sample_incidents.generate_incidents()
    with realistic modelling (urgency, distance, time-of-day).
    """
    return generate_incidents(n=200, seed=_SEED)


def get_datalens_stats() -> dict:
    """Return aggregated statistics for DataLens dashboard."""
    rows = get_datalens_incidents()

    # By class
    by_class: dict[str, int] = {}
    for r in rows:
        cls = r["audio_class"]
        by_class[cls] = by_class.get(cls, 0) + 1

    # By status
    by_status: dict[str, int] = {}
    for r in rows:
        st = r["status"]
        by_status[st] = by_status.get(st, 0) + 1

    # By district
    by_district: dict[str, int] = {}
    for r in rows:
        d = r["district"]
        by_district[d] = by_district.get(d, 0) + 1

    # Average response time (resolved only)
    resolved = [r for r in rows if r["response_time_min"] is not None]
    avg_response = (
        round(sum(r["response_time_min"] for r in resolved) / len(resolved), 1)
        if resolved
        else 0
    )

    # Incidents per day (last 30 days)
    total = len(rows)
    daily_avg = round(total / 30, 1)

    return {
        "total_incidents": total,
        "by_class": by_class,
        "by_status": by_status,
        "by_district": by_district,
        "avg_response_time_min": avg_response,
        "daily_average": daily_avg,
        "detection_rate": round(by_status.get("resolved", 0) / max(total, 1) * 100, 1),
        "false_alarm_rate": round(
            by_status.get("false_alarm", 0) / max(total, 1) * 100, 1
        ),
    }
